"""Interactive helper that turns a short-lived user token into a never-expiring
Page token + IG_USER_ID and writes them to .env.

Usage:
    instagram-mcp-get-token
"""
from __future__ import annotations

import getpass
import json
import pathlib
import re
import sys
import unicodedata

import httpx

GRAPH = "https://graph.facebook.com/v21.0"


def _slug(name: str) -> str:
    """A safe alias from a name: transliterate accents (Á -> a), keep [a-z0-9_]."""
    decomposed = unicodedata.normalize("NFKD", name)
    ascii_name = "".join(c for c in decomposed if not unicodedata.combining(c))
    slug = re.sub(r"[^a-z0-9]+", "_", ascii_name.lower()).strip("_")
    return slug or "account"


def _api(path: str, **params: str) -> dict:
    # httpx bundles CA certs (certifi); plain urllib fails TLS on python.org Python.
    r = httpx.get(f"{GRAPH}/{path.lstrip('/')}", params=params, timeout=30.0)
    body = r.json()
    if "error" in body:
        raise SystemExit(f"Graph API error: {body['error']}")
    return body


def _prompt(label: str, secret: bool = False) -> str:
    val = (getpass.getpass(f"{label}: ") if secret else input(f"{label}: ")).strip()
    if not val:
        raise SystemExit(f"{label} is required")
    return val


def main() -> None:
    print("Instagram MCP — token setup")
    print("=" * 40)
    print(
        "You'll need:\n"
        "  1. Your Meta App ID and App Secret (from App Dashboard → Settings → Basic)\n"
        "  2. A short-lived User Token from Graph API Explorer with the scopes:\n"
        "     instagram_basic, instagram_content_publish, instagram_manage_comments,\n"
        "     instagram_manage_messages, instagram_manage_insights, pages_show_list,\n"
        "     pages_read_engagement, business_management\n"
    )

    app_id = _prompt("App ID")
    app_secret = _prompt("App Secret", secret=True)
    short_token = _prompt("Short-lived user token", secret=True)

    print("\n[1/3] Exchanging for long-lived user token...")
    long_user = _api(
        "oauth/access_token",
        grant_type="fb_exchange_token",
        client_id=app_id,
        client_secret=app_secret,
        fb_exchange_token=short_token,
    )["access_token"]
    print("      done.")

    print("[2/3] Listing your Pages with linked Instagram accounts...")
    pages = _api(
        "me/accounts",
        fields="id,name,instagram_business_account{id,username},access_token",
        access_token=long_user,
    )["data"]
    linked = [p for p in pages if p.get("instagram_business_account")]
    if not linked:
        raise SystemExit(
            "No Pages with linked Instagram Business/Creator accounts. "
            "Switch your IG account to Business/Creator and link it to a Facebook Page."
        )

    print()
    for i, p in enumerate(linked, 1):
        ig = p["instagram_business_account"]
        print(f"  {i}. @{ig['username']}  (Page: {p['name']})")

    choice = _prompt(f"\nPick an account [1-{len(linked)}]")
    try:
        idx = int(choice) - 1
        page = linked[idx]
    except (ValueError, IndexError) as e:
        raise SystemExit("Invalid selection") from e

    page_token = page["access_token"]
    ig_user_id = page["instagram_business_account"]["id"]
    ig_username = page["instagram_business_account"]["username"]
    fb_page_id = page["id"]
    print(f"      selected @{ig_username}  (IG user ID {ig_user_id}, Page ID {fb_page_id}).")

    print("[3/3] Writing .env...")
    env_path = pathlib.Path(".env")
    contents = (
        f"# Generated by instagram-mcp-get-token\n"
        f"IG_USER_ID={ig_user_id}\n"
        f"IG_ACCESS_TOKEN={page_token}\n"
        f"IG_GRAPH_VERSION=v21.0\n"
        f"IG_GRAPH_HOST=graph.facebook.com\n"
    )
    if env_path.exists():
        backup = env_path.with_suffix(".env.bak")
        backup.write_text(env_path.read_text())
        print(f"      existing .env backed up to {backup}")
    env_path.write_text(contents)
    print(f"      wrote {env_path.resolve()}")

    alias = _slug(ig_username)
    print("\nFor a multi-account setup, add this entry to IG_ACCOUNTS:")
    print(
        json.dumps(
            {alias: {"user_id": ig_user_id, "token": page_token, "fb_page_id": fb_page_id}}
        )
    )

    print("\nAll set. Test it with:")
    print(
        '  python -c "import asyncio; '
        'from instagram_mcp.server import get_my_profile; '
        'print(asyncio.run(get_my_profile()))"'
    )


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\naborted.", file=sys.stderr)
        sys.exit(130)
